version: '3.8'

services:
  nightflux:
    image: ghcr.io/nielsmaerten/nightflux:latest
    environment:
      # Required configuration options:
      NIGHTFLUX_NIGHTSCOUT_URL: https://your-nightscout-instance.example.com
      NIGHTFLUX_NIGHTSCOUT_TOKEN: your-nightscout-api-token
      NIGHTFLUX_INFLUXDB_URL: http://localhost:8086
      NIGHTFLUX_INFLUXDB_ORG: your-org-name
      NIGHTFLUX_INFLUXDB_BUCKET: nightscout-data
      NIGHTFLUX_INFLUXDB_TOKEN: your-influxdb-token
      NIGHTFLUX_CRON_SCHEDULE: "*/10 * * * *" # Run every 10 minutes
      NIGHTFLUX_RUN_ONCE: 1
      # Optional configuration options:
      # See .env.example
    volumes:
      - ./logs:/usr/src/app/logs
    restart: no