name: Build binaries

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-upload:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary_name: nightflux-linux
          - os: windows-latest
            binary_name: nightflux-windows.exe
          - os: macos-latest
            binary_name: nightflux-macos
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Compile project
        run: bun compile src/nightflux.ts --outfile ${{ matrix.binary_name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: ${{ matrix.binary_name }}
          path: ${{ matrix.binary_name }}
          if-no-files-found: 'warn'
          retention-days: 7
          compression-level: 9
          overwrite: false
