name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - run: npm i
      - run: npm run build
      - run: npm run typecheck
      - run: npm run format:check
      - run: npm test > /dev/null 2>&1
        env:
          NIGHTSCOUT_URL: ${{secrets.NIGHTSCOUT_URL}}
